import { StyleSheet } from "react-native";
import { RFPercentage, RFValue } from "react-native-responsive-fontsize";

export const messageBubbleStyles = StyleSheet.create({
    messageContainer: {
        minWidth: '24%',
        marginVertical: 8,
        marginHorizontal: 10,
        flexDirection: 'row',
        shadowColor: 'black',
        shadowOffset: { width: 1, height: 1 },
        shadowRadius: 5,
        shadowOpacity: 0.2,
        elevation: 10,
        borderRadius: 20,
    },
    messageText: {
        fontSize: RFValue(11.4),
        color: 'white',
        fontWeight: '600',
        marginVertical: 15,
        marginBottom: 25,
        marginRight: 15,
    },
    img: {
        height: RFPercentage(20),
        width: RFPercentage(35),
        resizeMode: 'cover',
        left: -5,
        aspectRatio: 4 / 4,
        borderRadius: 20,
    },
    leftMessageArrow: {
        height: 0,
        width: 0,
        borderLeftWidth: 10,
        borderLeftColor: 'transparent',
        borderBottomColor: '#232E3B',
        borderBottomWidth: 10,
        alignSelf: 'flex-end',
        borderRightColor: 'black',
        right: 10,
        bottom: 0,
    },
    rightMessageArrow: {
        height: 0,
        position: 'absolute',
        width: 0,
        borderRightWidth: 10,
        borderRightColor: 'transparent',
        borderBottomColor: '#683EF3',
        borderBottomWidth: 10,
        alignSelf: 'flex-start',
        right: -8,
        bottom: 0,
    },
    timeAndReadContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        bottom: 4,
        position: 'absolute',
        paddingHorizontal: 10,
        gap: 2,
    },
    timeText: {
        fontSize: RFValue(9),
        fontWeight: '500',
        color: "rgba(255,255,255,0.6)",
    },
});